/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated/trends'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedMpoxRouteImport } from './routes/_authenticated/mpox'
import { Route as AuthenticatedMeaslesRouteImport } from './routes/_authenticated/measles'
import { Route as AuthenticatedIdsrRouteImport } from './routes/_authenticated/idsr'
import { Route as AuthenticatedFloodsRouteImport } from './routes/_authenticated/floods'
import { Route as AuthenticatedAnthraxRouteImport } from './routes/_authenticated/anthrax'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/_authenticated/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/_authenticated/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/_authenticated/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMpoxRoute = AuthenticatedMpoxRouteImport.update({
  id: '/_authenticated/mpox',
  path: '/mpox',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeaslesRoute = AuthenticatedMeaslesRouteImport.update({
  id: '/_authenticated/measles',
  path: '/measles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIdsrRoute = AuthenticatedIdsrRouteImport.update({
  id: '/_authenticated/idsr',
  path: '/idsr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFloodsRoute = AuthenticatedFloodsRouteImport.update({
  id: '/_authenticated/floods',
  path: '/floods',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnthraxRoute = AuthenticatedAnthraxRouteImport.update({
  id: '/_authenticated/anthrax',
  path: '/anthrax',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/anthrax': typeof AuthenticatedAnthraxRoute
  '/floods': typeof AuthenticatedFloodsRoute
  '/idsr': typeof AuthenticatedIdsrRoute
  '/measles': typeof AuthenticatedMeaslesRoute
  '/mpox': typeof AuthenticatedMpoxRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/anthrax': typeof AuthenticatedAnthraxRoute
  '/floods': typeof AuthenticatedFloodsRoute
  '/idsr': typeof AuthenticatedIdsrRoute
  '/measles': typeof AuthenticatedMeaslesRoute
  '/mpox': typeof AuthenticatedMpoxRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/anthrax': typeof AuthenticatedAnthraxRoute
  '/_authenticated/floods': typeof AuthenticatedFloodsRoute
  '/_authenticated/idsr': typeof AuthenticatedIdsrRoute
  '/_authenticated/measles': typeof AuthenticatedMeaslesRoute
  '/_authenticated/mpox': typeof AuthenticatedMpoxRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/anthrax'
    | '/floods'
    | '/idsr'
    | '/measles'
    | '/mpox'
    | '/nutrition'
    | '/support'
    | '/trends'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anthrax'
    | '/floods'
    | '/idsr'
    | '/measles'
    | '/mpox'
    | '/nutrition'
    | '/support'
    | '/trends'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/anthrax'
    | '/_authenticated/floods'
    | '/_authenticated/idsr'
    | '/_authenticated/measles'
    | '/_authenticated/mpox'
    | '/_authenticated/nutrition'
    | '/_authenticated/support'
    | '/_authenticated/trends'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAnthraxRoute: typeof AuthenticatedAnthraxRoute
  AuthenticatedFloodsRoute: typeof AuthenticatedFloodsRoute
  AuthenticatedIdsrRoute: typeof AuthenticatedIdsrRoute
  AuthenticatedMeaslesRoute: typeof AuthenticatedMeaslesRoute
  AuthenticatedMpoxRoute: typeof AuthenticatedMpoxRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mpox': {
      id: '/_authenticated/mpox'
      path: '/mpox'
      fullPath: '/mpox'
      preLoaderRoute: typeof AuthenticatedMpoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/measles': {
      id: '/_authenticated/measles'
      path: '/measles'
      fullPath: '/measles'
      preLoaderRoute: typeof AuthenticatedMeaslesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/idsr': {
      id: '/_authenticated/idsr'
      path: '/idsr'
      fullPath: '/idsr'
      preLoaderRoute: typeof AuthenticatedIdsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/floods': {
      id: '/_authenticated/floods'
      path: '/floods'
      fullPath: '/floods'
      preLoaderRoute: typeof AuthenticatedFloodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/anthrax': {
      id: '/_authenticated/anthrax'
      path: '/anthrax'
      fullPath: '/anthrax'
      preLoaderRoute: typeof AuthenticatedAnthraxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAnthraxRoute: AuthenticatedAnthraxRoute,
  AuthenticatedFloodsRoute: AuthenticatedFloodsRoute,
  AuthenticatedIdsrRoute: AuthenticatedIdsrRoute,
  AuthenticatedMeaslesRoute: AuthenticatedMeaslesRoute,
  AuthenticatedMpoxRoute: AuthenticatedMpoxRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
