/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated/trends'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedMpoxRouteImport } from './routes/_authenticated/mpox'
import { Route as AuthenticatedMeaslesRouteImport } from './routes/_authenticated/measles'
import { Route as AuthenticatedIdsrRouteImport } from './routes/_authenticated/idsr'
import { Route as AuthenticatedFloodsRouteImport } from './routes/_authenticated/floods'
import { Route as AuthenticatedAnthraxRouteImport } from './routes/_authenticated/anthrax'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMpoxRoute = AuthenticatedMpoxRouteImport.update({
  id: '/mpox',
  path: '/mpox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeaslesRoute = AuthenticatedMeaslesRouteImport.update({
  id: '/measles',
  path: '/measles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdsrRoute = AuthenticatedIdsrRouteImport.update({
  id: '/idsr',
  path: '/idsr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFloodsRoute = AuthenticatedFloodsRouteImport.update({
  id: '/floods',
  path: '/floods',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnthraxRoute = AuthenticatedAnthraxRouteImport.update({
  id: '/anthrax',
  path: '/anthrax',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/anthrax': typeof AuthenticatedAnthraxRoute
  '/floods': typeof AuthenticatedFloodsRoute
  '/idsr': typeof AuthenticatedIdsrRoute
  '/measles': typeof AuthenticatedMeaslesRoute
  '/mpox': typeof AuthenticatedMpoxRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trends': typeof AuthenticatedTrendsRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/anthrax': typeof AuthenticatedAnthraxRoute
  '/floods': typeof AuthenticatedFloodsRoute
  '/idsr': typeof AuthenticatedIdsrRoute
  '/measles': typeof AuthenticatedMeaslesRoute
  '/mpox': typeof AuthenticatedMpoxRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/anthrax': typeof AuthenticatedAnthraxRoute
  '/_authenticated/floods': typeof AuthenticatedFloodsRoute
  '/_authenticated/idsr': typeof AuthenticatedIdsrRoute
  '/_authenticated/measles': typeof AuthenticatedMeaslesRoute
  '/_authenticated/mpox': typeof AuthenticatedMpoxRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/anthrax'
    | '/floods'
    | '/idsr'
    | '/measles'
    | '/mpox'
    | '/nutrition'
    | '/support'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/anthrax'
    | '/floods'
    | '/idsr'
    | '/measles'
    | '/mpox'
    | '/nutrition'
    | '/support'
    | '/trends'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/anthrax'
    | '/_authenticated/floods'
    | '/_authenticated/idsr'
    | '/_authenticated/measles'
    | '/_authenticated/mpox'
    | '/_authenticated/nutrition'
    | '/_authenticated/support'
    | '/_authenticated/trends'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mpox': {
      id: '/_authenticated/mpox'
      path: '/mpox'
      fullPath: '/mpox'
      preLoaderRoute: typeof AuthenticatedMpoxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/measles': {
      id: '/_authenticated/measles'
      path: '/measles'
      fullPath: '/measles'
      preLoaderRoute: typeof AuthenticatedMeaslesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/idsr': {
      id: '/_authenticated/idsr'
      path: '/idsr'
      fullPath: '/idsr'
      preLoaderRoute: typeof AuthenticatedIdsrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/floods': {
      id: '/_authenticated/floods'
      path: '/floods'
      fullPath: '/floods'
      preLoaderRoute: typeof AuthenticatedFloodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anthrax': {
      id: '/_authenticated/anthrax'
      path: '/anthrax'
      fullPath: '/anthrax'
      preLoaderRoute: typeof AuthenticatedAnthraxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnthraxRoute: typeof AuthenticatedAnthraxRoute
  AuthenticatedFloodsRoute: typeof AuthenticatedFloodsRoute
  AuthenticatedIdsrRoute: typeof AuthenticatedIdsrRoute
  AuthenticatedMeaslesRoute: typeof AuthenticatedMeaslesRoute
  AuthenticatedMpoxRoute: typeof AuthenticatedMpoxRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnthraxRoute: AuthenticatedAnthraxRoute,
  AuthenticatedFloodsRoute: AuthenticatedFloodsRoute,
  AuthenticatedIdsrRoute: AuthenticatedIdsrRoute,
  AuthenticatedMeaslesRoute: AuthenticatedMeaslesRoute,
  AuthenticatedMpoxRoute: AuthenticatedMpoxRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
